# Generated by Django 3.2.6 on 2023-03-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
