# Generated by Django 3.2.6 on 2023-03-29 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0002_city_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
    ]
