# Generated by Django 4.1.7 on 2023-03-23 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Адрес')),
                ('companyName', models.CharField(blank=True, max_length=300, verbose_name='Название магазина')),
                ('adminPhone', models.CharField(max_length=300, null=True, verbose_name='Номер Админ')),
                ('adminName', models.CharField(max_length=300, null=True, verbose_name='Имя Админа')),
                ('logoUrl', models.FileField(blank=True, null=True, upload_to='')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shops', to=settings.AUTH_USER_MODEL, verbose_name='Админ')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('sku', models.CharField(max_length=300, verbose_name='Код товара')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('old_price', models.IntegerField(blank=True, null=True, verbose_name='Старая цена')),
                ('manufacturer', models.CharField(max_length=300, null=True, verbose_name='Производитель')),
                ('count', models.IntegerField(default=0, verbose_name='Количество')),
                ('created_date', models.DateTimeField(verbose_name='Дата создания')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='Скрыть')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.shop')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ShopOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[('waiting_for_payment', 'Ожидает оплаты'), ('paid', 'Оплачено'), ('canceled', 'Отменено'), ('partially_paid', 'Оплачено частично (только бонусами)')], default='waiting_for_payment', max_length=300, verbose_name='Статус оплаты')),
                ('status', models.CharField(choices=[('proceed', 'Готов к выдаче'), ('pending', 'pending'), ('canceled', 'Отменен'), ('finished', 'Завершен')], default='proceed', max_length=300, verbose_name='Статус заказа')),
                ('preferred_pickup_date', models.DateTimeField(blank=True, null=True, verbose_name='Предпочитаемая дата выдачи')),
                ('total_price', models.IntegerField(default=0, verbose_name='Полная сумма')),
                ('use_bonus', models.BooleanField(default=False, verbose_name='Использовать бонусы для оплаты?')),
                ('price_without_bonus', models.IntegerField(default=0, verbose_name='Цена после списания бонусов')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания заказа')),
                ('qr_code', models.CharField(blank=True, max_length=500, null=True, verbose_name='QR-code')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения заказа')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shop', verbose_name='Магазин')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Транзакция заказа',
                'verbose_name_plural': 'Транзакция заказа',
            },
        ),
        migrations.CreateModel(
            name='ShopWorkTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lunch', models.BooleanField(default=False)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workTime', to='shop.shop')),
            ],
        ),
        migrations.CreateModel(
            name='ShopSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_name', models.IntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')], default=1)),
                ('first_half_from', models.TimeField(blank=True, null=True)),
                ('first_half_till', models.TimeField(blank=True, null=True)),
                ('second_half_from', models.TimeField(blank=True, null=True)),
                ('second_half_till', models.TimeField(blank=True, null=True)),
                ('work_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='shop.shopworktime')),
            ],
            options={
                'ordering': ['day_name'],
            },
        ),
        migrations.CreateModel(
            name='ShopOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1, verbose_name='Количество')),
                ('total_price', models.IntegerField(default=0, verbose_name='Общая сумма')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='shop.shopitem', verbose_name='Товар')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.shoporder')),
            ],
        ),
        migrations.CreateModel(
            name='ShopItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='', verbose_name='Фото')),
                ('is_cover_image', models.BooleanField(default=False, verbose_name='Использовать для оболжки')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.shopitem')),
            ],
        ),
        migrations.CreateModel(
            name='ShopItemDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('value', models.CharField(max_length=300, verbose_name='Значение')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='shop.shopitem')),
            ],
        ),
    ]
