# Generated by Django 3.2.6 on 2023-03-28 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoporderitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='shoporderitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='ShopOrder',
        ),
        migrations.DeleteModel(
            name='ShopOrderItem',
        ),
    ]
