# Generated by Django 3.2.6 on 2023-03-29 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_shop_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopworktime',
            options={'verbose_name': 'Время работы магазина'},
        ),
    ]
