# Generated by Django 3.2.6 on 2023-03-28 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0002_auto_20230328_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[('waiting_for_payment', 'Ожидает оплаты'), ('paid', 'Оплачено'), ('canceled', 'Отменено'), ('partially_paid', 'Оплачено частично (только бонусами)')], default='waiting_for_payment', max_length=300, verbose_name='Статус оплаты')),
                ('status', models.CharField(choices=[('proceed', 'Готов к выдаче'), ('pending', 'pending'), ('canceled', 'Отменен'), ('finished', 'Завершен')], default='proceed', max_length=300, verbose_name='Статус заказа')),
                ('preferred_pickup_date', models.DateTimeField(blank=True, null=True, verbose_name='Предпочитаемая дата выдачи')),
                ('total_price', models.IntegerField(default=0, verbose_name='Полная сумма')),
                ('use_bonus', models.BooleanField(default=False, verbose_name='Использовать бонусы для оплаты?')),
                ('price_without_bonus', models.IntegerField(default=0, verbose_name='Цена после списания бонусов')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания заказа')),
                ('qr_code', models.CharField(blank=True, max_length=500, null=True, verbose_name='QR-code')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения заказа')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shop', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Транзакция заказа',
                'verbose_name_plural': 'Транзакция заказа',
            },
        ),
        migrations.CreateModel(
            name='ShopOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1, verbose_name='Количество')),
                ('total_price', models.IntegerField(default=0, verbose_name='Общая сумма')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='shop.shopitem', verbose_name='Товар')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.shoporder')),
            ],
        ),
    ]
